@extends('survey::layouts.web_master')

@section('styles')

@endsection

@section('content')
    <div class="survey-container">
        <div class="survey-header">
            <h1>{{ $survey->title }}</h1>
            @if($survey->description)
                <p>{{ $survey->description }}</p>
            @endif
        </div>

        <div class="survey-progress-container">
            <div class="survey-progress-bar" id="survey-progress" style="width: 0%"></div>
        </div>

        <div class="survey-step-indicator" id="survey-step-indicator">
            <!-- Steps will be generated by JavaScript -->
        </div>

        <form id="survey-form" action="{{ route('survey.public.submit', $survey->access_token) }}" method="POST">
            @csrf

            @if(!auth()->check() && !$survey->requires_auth)
                <div class="survey-personal-info active" id="survey-personal-info">
                    <h3>اطلاعات شما</h3>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="survey-form-group">
                                <label for="name" class="survey-form-label">نام (اختیاری)</label>
                                <input type="text" id="name" name="name" class="survey-form-control" value="{{ old('name') }}" placeholder="نام خود را وارد کنید">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="survey-form-group">
                                <label for="email" class="survey-form-label">ایمیل (اختیاری)</label>
                                <input type="email" id="email" name="email" class="survey-form-control" value="{{ old('email') }}" placeholder="ایمیل خود را وارد کنید">
                            </div>
                        </div>
                    </div>

                    <div class="survey-navigation-buttons d-flex justify-content-between mt-3">
                        <div></div>
                        <button type="button" class="survey-btn survey-btn-primary survey-next-button">
                            <span>بعدی</span>
                            <i class="fas fa-arrow-left ml-2"></i>
                        </button>
                    </div>
                </div>
            @endif

            @foreach($survey->questions as $index => $question)
                <div class="survey-question-container {{ ($index == 0 && (auth()->check() || $survey->requires_auth)) ? 'active' : '' }}"
                     id="survey-question-{{ $question->id }}"
                     data-question-id="{{ $question->id }}">

                    <div class="survey-question-text">
                        @if($question->is_required)
                            <span class="survey-required-badge">ضروری</span>
                        @endif
                        {{ $question->question_text }}
                    </div>

                    <div class="survey-question-options">
                        @switch($question->question_type)
                            @case(Modules\Survey\app\Enums\Database\QuestionTypeEnum::Single)
                                <div class="survey-single-choice-options">
                                    @foreach($question->options as $option)
                                        <div class="survey-option-item">
                                            <label>
                                                <input type="radio"
                                                       name="question_{{ $question->id }}"
                                                       value="{{ $option->id }}"
                                                    {{ old("question_{$question->id}") == $option->id ? 'checked' : '' }}>
                                                {{ $option->option_text }}
                                            </label>
                                        </div>
                                    @endforeach
                                </div>
                                <div class="survey-error-message" id="survey-error-{{ $question->id }}">
                                    <i class="fas fa-exclamation-circle me-2"></i> لطفاً یک گزینه را انتخاب کنید.
                                </div>
                                @break

                            @case(Modules\Survey\app\Enums\Database\QuestionTypeEnum::Multiple)
                                <div class="survey-multiple-choice-options">
                                    @foreach($question->options as $option)
                                        <div class="survey-option-item">
                                            <label>
                                                <input type="checkbox"
                                                       name="question_{{ $question->id }}[]"
                                                       value="{{ $option->id }}"
                                                    {{ is_array(old("question_{$question->id}")) && in_array($option->id, old("question_{$question->id}")) ? 'checked' : '' }}>
                                                {{ $option->option_text }}
                                            </label>
                                        </div>
                                    @endforeach
                                </div>
                                <div class="survey-error-message" id="survey-error-{{ $question->id }}">
                                    <i class="fas fa-exclamation-circle me-2"></i> لطفاً حداقل یک گزینه را انتخاب کنید.
                                </div>
                                @break

                            @case(Modules\Survey\app\Enums\Database\QuestionTypeEnum::Text)
                                <textarea class="survey-text-answer"
                                          name="question_{{ $question->id }}"
                                          rows="5"
                                          placeholder="پاسخ خود را اینجا بنویسید...">{{ old("question_{$question->id}") }}</textarea>
                                <div class="survey-error-message" id="survey-error-{{ $question->id }}">
                                    <i class="fas fa-exclamation-circle me-2"></i> لطفاً پاسخ خود را وارد کنید.
                                </div>
                                @break
                        @endswitch
                    </div>

                    <div class="survey-navigation-buttons d-flex justify-content-between mt-4">
                        @if($index > 0)
                            <button type="button" class="survey-btn survey-btn-secondary survey-prev-button">
                                <i class="fas fa-arrow-right me-2"></i> قبلی
                            </button>
                        @else
                            <div></div>
                        @endif

                        @if($index < count($survey->questions) - 1)
                            <button type="button" class="survey-btn survey-btn-primary survey-next-button">
                                بعدی <i class="fas fa-arrow-left ms-2"></i>
                            </button>
                        @else
                            <button type="submit" class="survey-btn survey-btn-success survey-submit-button">
                                <i class="fas fa-check me-2"></i> ثبت پاسخ‌ها
                            </button>
                        @endif
                    </div>
                </div>
            @endforeach
        </form>
    </div>
@endsection

@section('scripts')
    <!-- Bootstrap JS Bundle with Popper -->
    <script>
        $(document).ready(function() {
            const totalQuestions = {{ count($survey->questions) }};
            const hasPersonalInfoSection = {{ (!auth()->check() && !$survey->requires_auth) ? 'true' : 'false' }};
            const totalSteps = hasPersonalInfoSection ? totalQuestions + 1 : totalQuestions;
            let currentQuestionIndex = hasPersonalInfoSection ? 0 : 0;

// Create step indicators
            function createStepIndicators() {
                const stepIndicator = $('#survey-step-indicator');
                stepIndicator.empty();

                for (let i = 0; i < totalSteps; i++) {
                    const stepNumber = i + 1;
                    const isActive = i === currentQuestionIndex;
                    const isCompleted = i < currentQuestionIndex;

                    const stepClass = isActive ? 'active' : (isCompleted ? 'completed' : '');
                    const stepItem = $(`<div class="survey-step-bullet ${stepClass}">${stepNumber}</div>`);

                    stepIndicator.append(stepItem);
                }
            }

// Initialize step indicators
            createStepIndicators();

// Initialize progress bar
            updateProgressBar();

// Add touch-friendly behavior for options
            $('.survey-option-item').on('click', function(e) {
                if (e.target.tagName !== 'INPUT') {
                    const input = $(this).find('input');
                    if (input.attr('type') === 'radio') {
                        input.prop('checked', true);
                    } else if (input.attr('type') === 'checkbox') {
                        input.prop('checked', !input.prop('checked'));
                    }
                }
            });

// Handle next button click
            $('.survey-next-button').click(function() {
                const currentContainer = $(this).closest('.survey-question-container, .survey-personal-info');

// For personal info section
                if (currentContainer.hasClass('survey-personal-info')) {
                    moveToNextQuestion();
                    return;
                }

// For questions
                const questionId = currentContainer.data('question-id');

// Validate current question if required
                if (validateQuestion(questionId)) {
                    moveToNextQuestion();
                }
            });

// Handle previous button click
            $('.survey-prev-button').click(function() {
                moveToPreviousQuestion();
            });

// Handle form submission
            $('#survey-form').submit(function(e) {
                e.preventDefault();

// Get the last question
                const lastQuestionContainer = $('.survey-question-container').last();
                const lastQuestionId = lastQuestionContainer.data('question-id');

// Validate the last question if required
                if (validateQuestion(lastQuestionId)) {
// Submit the form if validation passes
                    $(this).find('.survey-submit-button').prop('disabled', true).html('<i class="fas fa-spinner fa-spin me-2"></i> در حال ارسال...');
                    this.submit();
                }
            });

// Function to validate a question
            function validateQuestion(questionId) {
                const questionContainer = $(`#survey-question-${questionId}`);
                const questionType = getQuestionType(questionContainer);
                const isRequired = questionContainer.find('.survey-required-badge').length > 0;

                if (!isRequired) {
                    return true;
                }

                let isValid = true;
                const errorMessage = $(`#survey-error-${questionId}`);

                switch (questionType) {
                    case 'single':
                        isValid = questionContainer.find('input[type="radio"]:checked').length > 0;
                        break;
                    case 'multiple':
                        isValid = questionContainer.find('input[type="checkbox"]:checked').length > 0;
                        break;
                    case 'text':
                        const textValue = questionContainer.find('textarea').val().trim();
                        isValid = textValue !== '';
                        break;
                }

                if (!isValid) {
                    errorMessage.show();
// Add shake animation
                    errorMessage.css('animation', 'shake 0.5s');
                    setTimeout(function() {
                        errorMessage.css('animation', '');
                    }, 500);

// Scroll to error
                    $('html, body').animate({
                        scrollTop: errorMessage.offset().top - 100
                    }, 300);
                } else {
                    errorMessage.hide();
                }

                return isValid;
            }

// Function to get question type
            function getQuestionType(questionContainer) {
                if (questionContainer.find('input[type="radio"]').length > 0) {
                    return 'single';
                } else if (questionContainer.find('input[type="checkbox"]').length > 0) {
                    return 'multiple';
                } else if (questionContainer.find('textarea').length > 0) {
                    return 'text';
                }
                return '';
            }

// Function to move to the next question
            function moveToNextQuestion() {
// Hide current question/section
                if (currentQuestionIndex === 0 && hasPersonalInfoSection) {
                    $('.survey-personal-info.active').removeClass('active');
                } else {
                    $('.survey-question-container.active').removeClass('active');
                }

// Increment index
                currentQuestionIndex++;

// Show next question
                if (hasPersonalInfoSection) {
// If we have a personal info section, adjust index for questions
                    $(`.survey-question-container:eq(${currentQuestionIndex - 1})`).addClass('active');
                } else {
                    $(`.survey-question-container:eq(${currentQuestionIndex})`).addClass('active');
                }

// Update progress bar and step indicators
                updateProgressBar();
                createStepIndicators();

// Scroll to top of the active question
                $('html, body').animate({
                    scrollTop: $('.survey-question-container.active, .survey-personal-info.active').offset().top - 20
                }, 300);
            }

// Function to move to the previous question
            function moveToPreviousQuestion() {
// Hide current question
                $('.survey-question-container.active').removeClass('active');

// Decrement index
                currentQuestionIndex--;

// Show previous question/section
                if (currentQuestionIndex === 0 && hasPersonalInfoSection) {
                    $('.survey-personal-info').addClass('active');
                } else {
                    if (hasPersonalInfoSection) {
                        $(`.survey-question-container:eq(${currentQuestionIndex - 1})`).addClass('active');
                    } else {
                        $(`.survey-question-container:eq(${currentQuestionIndex})`).addClass('active');
                    }
                }

// Update progress bar and step indicators
                updateProgressBar();
                createStepIndicators();

// Scroll to top of the active question
                $('html, body').animate({
                    scrollTop: $('.survey-question-container.active, .survey-personal-info.active').offset().top - 20
                }, 300);
            }

// Function to update progress bar
            function updateProgressBar() {
                const progress = (currentQuestionIndex / totalSteps) * 100;
                $('#survey-progress').css('width', `${progress}%`);
            }

// Initialize first section as active
            if (hasPersonalInfoSection) {
                $('.survey-personal-info').addClass('active');
            } else {
                $('.survey-question-container:first').addClass('active');
            }
        });
    </script>
@endsection
