@extends('survey::layouts.web_master')

@section('styles')
<style>
    /* Number input styling */
    .survey-number-input {
        margin-bottom: 10px;
    }

    .survey-number-answer {
        width: 100%;
        max-width: 300px;
        padding: 10px 15px;
        border: 1px solid #ddd;
        border-radius: 5px;
        font-size: 16px;
        transition: border-color 0.3s;
    }

    .survey-number-answer:focus {
        border-color: #040096;
        outline: none;
        box-shadow: 0 0 0 0.2rem rgba(4, 0, 150, 0.25);
    }

    .survey-number-answer::-webkit-inner-spin-button,
    .survey-number-answer::-webkit-outer-spin-button {
        opacity: 1;
        height: 20px;
        margin-right: 5px;
    }
    
    .survey-range-notice {
        font-size: 12px;
        color: #dc3545;
        margin-top: 5px;
        display: none;
    }
    
    /* Short text input styling */
    .survey-short-text-input {
        margin-bottom: 10px;
        position: relative;
    }

    .survey-short-text-answer {
        width: 100%;
        max-width: 600px;
        padding: 10px 15px;
        border: 1px solid #ddd;
        border-radius: 5px;
        font-size: 16px;
        transition: border-color 0.3s;
    }

    .survey-short-text-answer:focus {
        border-color: #040096;
        outline: none;
        box-shadow: 0 0 0 0.2rem rgba(4, 0, 150, 0.25);
    }
    
    .survey-char-counter {
        display: block;
        text-align: left;
        font-size: 12px;
        color: #777;
        margin-top: 5px;
        max-width: 600px;
    }
</style>
@endsection

@section('content')
    <div class="survey-container">
        <div class="survey-header">
            <h1>{{ $survey->title }}</h1>
            @if($survey->description)
                <p>{{ $survey->description }}</p>
            @endif
        </div>

        <div class="survey-progress-container">
            <div class="survey-progress-bar" id="survey-progress" style="width: 0%"></div>
        </div>

        <div class="survey-step-indicator" id="survey-step-indicator">
            <!-- Steps will be generated by JavaScript -->
        </div>

        <form id="survey-form" action="{{ route('survey.public.submit', $survey->access_token) }}" method="POST">
            @csrf
            @if($showPersonalInfo)
                <div class="survey-personal-info active" id="survey-personal-info">
                    <h3>اطلاعات شما</h3>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="survey-form-group">
                                <label for="name" class="survey-form-label">نام (اختیاری)</label>
                                <input type="text" id="name" name="name" class="survey-form-control"
                                       value="{{ old('name') }}" placeholder="نام خود را وارد کنید">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="survey-form-group">
                                <label for="email" class="survey-form-label">ایمیل (اختیاری)</label>
                                <input type="email" id="email" name="email" class="survey-form-control"
                                       value="{{ old('email') }}" placeholder="ایمیل خود را وارد کنید">
                                <small class="survey-error-message" id="email-validation-error" style="display: none;">
                                    <i class="fas fa-exclamation-circle me-2"></i> ایمیل وارد شده معتبر نیست.
                                </small>
                            </div>
                        </div>
                    </div>

                    <div class="survey-navigation-buttons d-flex justify-content-between mt-3">
                        <div></div>
                        <button type="button" class="survey-btn survey-btn-primary survey-next-button" id="personal-info-next">
                            <span>بعدی</span>
                            <i class="fas fa-arrow-left ml-2"></i>
                        </button>
                    </div>
                </div>
            @endif

            @foreach($survey->questions as $index => $question)
                <div
                    class="survey-question-container {{ ($index == 0 && !$showPersonalInfo) ? 'active' : '' }}"
                    id="survey-question-{{ $question->id }}"
                    data-question-id="{{ $question->id }}">

                    <div class="survey-question-text">
                        {{ $question->question_text }}
                        @if($question->is_required)
                            <span class="survey-required-badge">*</span>
                        @endif
                    </div>

                    <div class="survey-question-options">
                        @switch($question->question_type)
                            @case(Modules\Survey\app\Enums\Database\QuestionTypeEnum::Single)
                                <div class="survey-single-choice-options">
                                    @foreach($question->options as $option)
                                        <div class="survey-option-item">
                                            <label>
                                                <input type="radio"
                                                       name="question_{{ $question->id }}"
                                                       value="{{ $option->id }}"
                                                    {{ old("question_{$question->id}") == $option->id ? 'checked' : '' }}>
                                                {{ $option->option_text }}
                                            </label>
                                        </div>
                                    @endforeach
                                </div>
                                <div class="survey-error-message" id="survey-error-{{ $question->id }}" style="display: none;">
                                    <i class="fas fa-exclamation-circle me-2"></i> لطفاً یک گزینه را انتخاب کنید.
                                </div>
                                @break

                            @case(Modules\Survey\app\Enums\Database\QuestionTypeEnum::Multiple)
                                <div class="survey-multiple-choice-options">
                                    @foreach($question->options as $option)
                                        <div class="survey-option-item">
                                            <label>
                                                <input type="checkbox"
                                                       name="question_{{ $question->id }}[]"
                                                       value="{{ $option->id }}"
                                                    {{ is_array(old("question_{$question->id}")) && in_array($option->id, old("question_{$question->id}")) ? 'checked' : '' }}>
                                                {{ $option->option_text }}
                                            </label>
                                        </div>
                                    @endforeach
                                </div>
                                <div class="survey-error-message" id="survey-error-{{ $question->id }}" style="display: none;">
                                    <i class="fas fa-exclamation-circle me-2"></i> لطفاً حداقل یک گزینه را انتخاب کنید.
                                </div>
                                @break

                            @case(Modules\Survey\app\Enums\Database\QuestionTypeEnum::Text)
                                <textarea class="survey-text-answer"
                                          name="question_{{ $question->id }}"
                                          rows="5"
                                          placeholder="پاسخ خود را اینجا بنویسید...">{{ old("question_{$question->id}") }}</textarea>
                                <div class="survey-error-message" id="survey-error-{{ $question->id }}" style="display: none;">
                                    <i class="fas fa-exclamation-circle me-2"></i> لطفاً پاسخ خود را وارد کنید.
                                </div>
                                @break
                                
                            @case(Modules\Survey\app\Enums\Database\QuestionTypeEnum::ShortText)
                                @php
                                    $settings = $question->settings ?? [];
                                    $minLength = $settings['minLength'] ?? null;
                                    $maxLength = $settings['maxLength'] ?? null;
                                    $placeholder = $settings['placeholder'] ?? 'پاسخ خود را وارد کنید...';
                                @endphp
                                <div class="survey-short-text-input">
                                    <input type="text"
                                           class="survey-short-text-answer"
                                           name="question_{{ $question->id }}"
                                           {{ $minLength !== null ? "minlength={$minLength}" : '' }}
                                           {{ $maxLength !== null ? "maxlength={$maxLength}" : '' }}
                                           placeholder="{{ $placeholder }}"
                                           value="{{ old("question_{$question->id}") }}">
                                    @if($maxLength !== null)
                                        <div class="survey-char-counter">
                                            <span id="char-count-{{ $question->id }}">0</span> / {{ $maxLength }}
                                        </div>
                                    @endif
                                </div>
                                <div class="survey-error-message" id="survey-error-{{ $question->id }}" style="display: none;">
                                    <i class="fas fa-exclamation-circle me-2"></i> لطفاً پاسخ خود را وارد کنید.
                                </div>
                                @break

                            @case(Modules\Survey\app\Enums\Database\QuestionTypeEnum::Number)
                                @php
                                    $settings = $question->settings ?? [];
                                    $min = $settings['min'] ?? null;
                                    $max = $settings['max'] ?? null;
                                    $step = $settings['step'] ?? 'any';
                                    $default = $settings['default'] ?? null;
                                @endphp
                                <div class="survey-number-input">
                                    <input type="number"
                                           class="survey-number-answer"
                                           name="question_{{ $question->id }}"
                                           {{ $min !== null ? "min={$min}" : '' }}
                                           {{ $max !== null ? "max={$max}" : '' }}
                                           step="{{ $step }}"
                                           placeholder="مقدار عددی را وارد کنید"
                                           value="{{ old("question_{$question->id}") ?? $default }}">
                                    @if($min !== null && $max !== null)
                                        <div class="survey-range-notice" id="survey-range-notice-{{ $question->id }}" style="display: none;">
                                            <i class="fas fa-exclamation-circle me-1"></i> لطفاً عددی بین {{ $min }} و {{ $max }} وارد کنید.
                                        </div>
                                    @elseif($min !== null)
                                        <div class="survey-range-notice" id="survey-range-notice-{{ $question->id }}" style="display: none;">
                                            <i class="fas fa-exclamation-circle me-1"></i> لطفاً عددی بزرگتر یا مساوی {{ $min }} وارد کنید.
                                        </div>
                                    @elseif($max !== null)
                                        <div class="survey-range-notice" id="survey-range-notice-{{ $question->id }}" style="display: none;">
                                            <i class="fas fa-exclamation-circle me-1"></i> لطفاً عددی کوچکتر یا مساوی {{ $max }} وارد کنید.
                                        </div>
                                    @endif
                                </div>
                                <div class="survey-error-message" id="survey-error-{{ $question->id }}" style="display: none;">
                                    <i class="fas fa-exclamation-circle me-2"></i> لطفاً یک مقدار عددی وارد کنید.
                                </div>
                                @break
                        @endswitch
                    </div>

                    <div class="survey-navigation-buttons d-flex justify-content-between mt-4">
                        @if($index > 0 || $showPersonalInfo)
                            <button type="button" class="survey-btn survey-btn-secondary survey-prev-button">
                                <i class="fas fa-arrow-right me-2"></i> قبلی
                            </button>
                        @else
                            <div></div>
                        @endif

                        @if($index < count($survey->questions) - 1)
                            <button type="button" class="survey-btn survey-btn-primary survey-next-button" style="display: none;">
                                بعدی <i class="fas fa-arrow-left ms-2"></i>
                            </button>
                        @else
                            <button type="submit" class="survey-btn survey-btn-success survey-submit-button" style="display: none;">
                                <i class="fas fa-check me-2"></i> ثبت پاسخ‌ها
                            </button>
                        @endif
                    </div>
                </div>
            @endforeach
        </form>
    </div>
    <div class="survey-footer text-center mt-4">
        <p class="small gradient-text">تارینوتک، مسیر موفقیت دیجیتال</p>
    </div>
@endsection

@section('scripts')
    <!-- Bootstrap JS Bundle with Popper -->
    <script>
        $(document).ready(function () {
            const totalQuestions = {{ count($survey->questions) }};
            const hasPersonalInfoSection = {{ $showPersonalInfo ? 'true' : 'false' }};
            const totalSteps = hasPersonalInfoSection ? totalQuestions + 1 : totalQuestions;
            let currentQuestionIndex = 0; // Always start at 0
            
            console.log('Survey initialized with:', {
                totalQuestions,
                hasPersonalInfoSection,
                totalSteps,
                currentQuestionIndex
            });

            // Create step indicators
            function createStepIndicators() {
                const stepIndicator = $('#survey-step-indicator');
                stepIndicator.empty();

                for (let i = 0; i < totalSteps; i++) {
                    const stepNumber = i + 1;
                    const isActive = i === currentQuestionIndex;
                    const isCompleted = i < currentQuestionIndex;

                    const stepClass = isActive ? 'active' : (isCompleted ? 'completed' : '');
                    const stepItem = $(`<div class="survey-step-bullet ${stepClass}">${stepNumber}</div>`);

                    stepIndicator.append(stepItem);
                }
            }

            // Initialize step indicators
            createStepIndicators();

            // Initialize progress bar
            updateProgressBar();

            // Email validation
            $('#email').on('input', function() {
                validateEmail($(this).val());
            });

            function validateEmail(email) {
                const errorElement = $('#email-validation-error');

                if (!email) {
                    // Empty is fine since it's optional
                    errorElement.hide();
                    return true;
                }

                const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
                const isValid = emailPattern.test(email);

                if (isValid) {
                    errorElement.hide();
                    return true;
                } else {
                    errorElement.show();
                    return false;
                }
            }

            // Add validation to the personal info next button
            $('#personal-info-next').click(function() {
                const emailValue = $('#email').val();
                if (emailValue && !validateEmail(emailValue)) {
                    // Don't proceed if email is invalid
                    $('#email').focus();
                    return;
                }
                moveToNextQuestion();
            });

            // Improve option click behavior
            $('.survey-option-item').on('click', function(e) {
                const input = $(this).find('input');
                const questionContainer = $(this).closest('.survey-question-container');
                const isRadio = input.attr('type') === 'radio';
                
                // Toggle or set the checked state
                if (isRadio) {
                    // For radio buttons, uncheck all other options in the same group
                    const name = input.attr('name');
                    $(`input[name="${name}"]`).prop('checked', false).closest('.survey-option-item').removeClass('selected');
                    input.prop('checked', true);
                    $(this).addClass('selected');
                    
                    // Show next button (might be needed for the last question's submit button)
                    questionContainer.find('.survey-next-button, .survey-submit-button').show();
                    
                    // Auto-navigate to the next question after a short delay
                    setTimeout(function() {
                        // Get the current active question container
                        const activeContainer = $('.survey-question-container.active');
                        
                        // Make sure we're still on the same question (user might have clicked quickly)
                        if (activeContainer.data('question-id') !== questionContainer.data('question-id')) {
                            return; // We've already moved, don't proceed
                        }
                        
                        // Get current question index for tracking
                        const currentVisibleIndex = hasPersonalInfoSection ? 
                            currentQuestionIndex - 1 : currentQuestionIndex;
                        console.log('Current question index before move:', currentVisibleIndex);
                        
                        // Validate the question before moving
                        const questionId = questionContainer.data('question-id');
                        if (validateQuestion(questionId)) {
                            // If this is the last question with a submit button, don't auto-navigate
                            if (questionContainer.find('.survey-submit-button').length > 0) {
                                // Don't auto-submit to give user a chance to review
                                console.log('Last question - not auto-submitting');
                            } else {
                                // Otherwise move to next question
                                console.log('Moving to next question from index:', currentVisibleIndex);
                                moveToNextQuestion();
                            }
                        }
                    }, 500); // Half-second delay for better user experience
                    
                } else if (input.attr('type') === 'checkbox') {
                    // For checkboxes, just toggle the current one
                    const newState = !input.prop('checked');
                    input.prop('checked', newState);
                    $(this).toggleClass('selected', newState);
                    
                    // Show next button if at least one option is selected
                    if (questionContainer.find('input[type="checkbox"]:checked').length > 0) {
                        questionContainer.find('.survey-next-button, .survey-submit-button').show();
                    } else {
                        questionContainer.find('.survey-next-button, .survey-submit-button').hide();
                    }
                }
            });
            
            // Adding direct click handler for radio inputs to handle label-less clicks
            $('.survey-single-choice-options input[type="radio"]').on('click', function(e) {
                // Prevent the event from bubbling to avoid duplicate handling
                e.stopPropagation();
                
                const questionContainer = $(this).closest('.survey-question-container');
                $(this).closest('.survey-option-item').addClass('selected');
                
                // Auto-navigate after a short delay
                setTimeout(function() {
                    // Get the current active question container
                    const activeContainer = $('.survey-question-container.active');
                    
                    // Make sure we're still on the same question (user might have clicked quickly)
                    if (activeContainer.data('question-id') !== questionContainer.data('question-id')) {
                        return; // We've already moved, don't proceed
                    }
                    
                    const questionId = questionContainer.data('question-id');
                    if (validateQuestion(questionId)) {
                        if (questionContainer.find('.survey-submit-button').length > 0) {
                            // Don't auto-submit to give user a chance to review
                            console.log('Last question - not auto-submitting');
                        } else {
                            console.log('Moving to next question from radio direct click');
                            moveToNextQuestion();
                        }
                    }
                }, 500);
            });
            
            // Handle text input - show next button when text is entered
            $('.survey-text-answer').on('input', function() {
                const questionContainer = $(this).closest('.survey-question-container');
                if ($(this).val().trim() !== '') {
                    questionContainer.find('.survey-next-button, .survey-submit-button').show();
                } else {
                    questionContainer.find('.survey-next-button, .survey-submit-button').hide();
                }
            });
            
            // Handle short text input - show next button when text is entered
            $('.survey-short-text-answer').on('input', function() {
                const $this = $(this);
                const questionContainer = $this.closest('.survey-question-container');
                const questionId = questionContainer.data('question-id');
                const charCountEl = $(`#char-count-${questionId}`);
                
                // Update character count if counter exists
                if (charCountEl.length > 0) {
                    charCountEl.text($this.val().length);
                }
                
                if ($this.val().trim() !== '') {
                    questionContainer.find('.survey-next-button, .survey-submit-button').show();
                } else {
                    questionContainer.find('.survey-next-button, .survey-submit-button').hide();
                }
            });
            
            // Handle number input - show next button when a number is entered and validate range
            $('.survey-number-answer').on('input', function() {
                const $this = $(this);
                const questionContainer = $this.closest('.survey-question-container');
                const questionId = questionContainer.data('question-id');
                const rangeNotice = $(`#survey-range-notice-${questionId}`);
                
                // Show next button if a value is entered
                if ($this.val().trim() !== '') {
                    questionContainer.find('.survey-next-button, .survey-submit-button').show();
                    
                    // Check range constraints if they exist
                    const value = parseFloat($this.val());
                    const min = $this.attr('min') ? parseFloat($this.attr('min')) : null;
                    const max = $this.attr('max') ? parseFloat($this.attr('max')) : null;
                    
                    // Only show range error if the value is outside of constraints
                    if ((min !== null && value < min) || (max !== null && value > max)) {
                        rangeNotice.show();
                    } else {
                        rangeNotice.hide();
                    }
                } else {
                    questionContainer.find('.survey-next-button, .survey-submit-button').hide();
                    rangeNotice.hide(); // Hide range notice when field is empty
                }
            });
            
            // Mark initially selected options and show next button if needed
            $('.survey-option-item input:checked').each(function() {
                $(this).closest('.survey-option-item').addClass('selected');
                $(this).closest('.survey-question-container').find('.survey-next-button, .survey-submit-button').show();
            });
            
            // Show next button if text is already entered
            $('.survey-text-answer').each(function() {
                if ($(this).val().trim() !== '') {
                    $(this).closest('.survey-question-container').find('.survey-next-button, .survey-submit-button').show();
                }
            });
            
            // Initialize number inputs - check ranges and show notices if needed
            $('.survey-number-answer').each(function() {
                const $this = $(this);
                const questionContainer = $this.closest('.survey-question-container');
                const questionId = questionContainer.data('question-id');
                const rangeNotice = $(`#survey-range-notice-${questionId}`);
                
                if ($this.val().trim() !== '') {
                    // Check range constraints if value exists
                    const value = parseFloat($this.val());
                    const min = $this.attr('min') ? parseFloat($this.attr('min')) : null;
                    const max = $this.attr('max') ? parseFloat($this.attr('max')) : null;
                    
                    // Only show range error if the value is outside of constraints
                    if ((min !== null && value < min) || (max !== null && value > max)) {
                        rangeNotice.show();
                    } else {
                        rangeNotice.hide();
                    }
                    
                    // Show next button
                    questionContainer.find('.survey-next-button, .survey-submit-button').show();
                }
            });
            
            // Initialize character counters and show next button for short text inputs
            $('.survey-short-text-answer').each(function() {
                const $this = $(this);
                const questionContainer = $this.closest('.survey-question-container');
                const questionId = questionContainer.data('question-id');
                const charCountEl = $(`#char-count-${questionId}`);
                
                if (charCountEl.length > 0) {
                    charCountEl.text($this.val().length);
                }
                
                if ($this.val().trim() !== '') {
                    questionContainer.find('.survey-next-button, .survey-submit-button').show();
                }
            });

            // Handle next button click (excluding personal info which is handled separately)
            $('.survey-next-button:not(#personal-info-next)').click(function () {
                const currentContainer = $(this).closest('.survey-question-container');

                // For questions
                const questionId = currentContainer.data('question-id');

                // Validate current question if required
                if (validateQuestion(questionId)) {
                    moveToNextQuestion();
                }
            });

            // Handle previous button click
            $('.survey-prev-button').click(function () {
                moveToPreviousQuestion();
            });

            // Handle form submission
            $('#survey-form').submit(function (e) {
                e.preventDefault();

                // Get the last question
                const lastQuestionContainer = $('.survey-question-container').last();
                const lastQuestionId = lastQuestionContainer.data('question-id');

                // Validate the last question if required
                if (validateQuestion(lastQuestionId)) {
                    // Submit the form if validation passes
                    $(this).find('.survey-submit-button').prop('disabled', true).html('<i class="fas fa-spinner fa-spin me-2"></i> در حال ارسال...');
                    this.submit();
                }
            });

            // Function to validate a question
            function validateQuestion(questionId) {
                const questionContainer = $(`#survey-question-${questionId}`);
                const questionType = getQuestionType(questionContainer);
                const isRequired = questionContainer.find('.survey-required-badge').length > 0;

                if (!isRequired) {
                    return true;
                }

                let isValid = true;
                const errorMessage = $(`#survey-error-${questionId}`);

                switch (questionType) {
                    case 'single':
                        isValid = questionContainer.find('input[type="radio"]:checked').length > 0;
                        break;
                    case 'multiple':
                        isValid = questionContainer.find('input[type="checkbox"]:checked').length > 0;
                        break;
                    case 'text':
                        const textValue = questionContainer.find('textarea').val().trim();
                        isValid = textValue !== '';
                        break;
                    case 'short-text':
                        const shortTextValue = questionContainer.find('input[type="text"]').val().trim();
                        isValid = shortTextValue !== '';
                        
                        // Check minLength constraint if set
                        const minLength = questionContainer.find('input[type="text"]').attr('minlength');
                        if (isValid && minLength && shortTextValue.length < parseInt(minLength)) {
                            isValid = false;
                            errorMessage.text(`لطفاً حداقل ${minLength} کاراکتر وارد کنید.`);
                        }
                        break;
                    case 'number':
                        const numberInput = questionContainer.find('input[type="number"]');
                        const numberValue = numberInput.val().trim();

                        // Check if the value is not empty
                        if (numberValue === '') {
                            isValid = false;
                            break;
                        }

                        // Check if the value is a valid number
                        const numValue = parseFloat(numberValue);
                        if (isNaN(numValue)) {
                            isValid = false;
                            break;
                        }

                        // Check min/max constraints
                        const min = numberInput.attr('min') ? parseFloat(numberInput.attr('min')) : null;
                        const max = numberInput.attr('max') ? parseFloat(numberInput.attr('max')) : null;
                        const rangeNotice = $(`#survey-range-notice-${questionId}`);

                        if (min !== null && numValue < min) {
                            isValid = false;
                            rangeNotice.show(); // Show the range notice
                            errorMessage.hide(); // Hide the generic error message since we're showing the specific one
                        } else if (max !== null && numValue > max) {
                            isValid = false;
                            rangeNotice.show(); // Show the range notice
                            errorMessage.hide(); // Hide the generic error message since we're showing the specific one
                        } else {
                            rangeNotice.hide(); // Hide the range notice if value is valid
                        }
                        break;
                }

                if (!isValid) {
                    // For number fields with range errors, scroll to the range notice if it's visible
                    if (questionType === 'number' && $(`#survey-range-notice-${questionId}`).is(':visible')) {
                        // Add shake animation to range notice
                        const rangeNotice = $(`#survey-range-notice-${questionId}`);
                        rangeNotice.css('animation', 'shake 0.5s');
                        setTimeout(function () {
                            rangeNotice.css('animation', '');
                        }, 500);
                        
                        // Scroll to the range notice
                        $('html, body').animate({
                            scrollTop: rangeNotice.offset().top - 100
                        }, 300);
                    } else {
                        // For other errors, use the standard error message
                        errorMessage.show();
                        // Add shake animation
                        errorMessage.css('animation', 'shake 0.5s');
                        setTimeout(function () {
                            errorMessage.css('animation', '');
                        }, 500);

                        // Scroll to error
                        $('html, body').animate({
                            scrollTop: errorMessage.offset().top - 100
                        }, 300);
                    }
                } else {
                    errorMessage.hide();
                    if (questionType === 'number') {
                        $(`#survey-range-notice-${questionId}`).hide();
                    }
                }

                return isValid;
            }

            // Function to get question type
            function getQuestionType(questionContainer) {
                if (questionContainer.find('input[type="radio"]').length > 0) {
                    return 'single';
                } else if (questionContainer.find('input[type="checkbox"]').length > 0) {
                    return 'multiple';
                } else if (questionContainer.find('textarea').length > 0) {
                    return 'text';
                } else if (questionContainer.find('input[type="number"]').length > 0) {
                    return 'number';
                } else if (questionContainer.find('input[type="text"].survey-short-text-answer').length > 0) {
                    return 'short-text';
                }
                return '';
            }

            // Function to move to the next question
            function moveToNextQuestion() {
                // Get the current active container
                const currentContainer = $('.survey-question-container.active, .survey-personal-info.active');
                
                // Store the current question index before we update it
                const previousIndex = currentQuestionIndex;
                
                // Hide current question/section
                if (currentQuestionIndex === 0 && hasPersonalInfoSection) {
                    $('.survey-personal-info.active').removeClass('active');
                } else {
                    $('.survey-question-container.active').removeClass('active');
                }

                // Increment index
                currentQuestionIndex++;

                // Find the next container to show
                let nextContainer;
                if (hasPersonalInfoSection) {
                    // If we have a personal info section, adjust index for questions
                    nextContainer = $(`.survey-question-container:eq(${currentQuestionIndex - 1})`);
                } else {
                    nextContainer = $(`.survey-question-container:eq(${currentQuestionIndex})`);
                }
                
                // Make sure we actually found a next container
                if (nextContainer.length === 0) {
                    // If not found, revert to previous index and container
                    currentQuestionIndex = previousIndex;
                    currentContainer.addClass('active');
                    console.error('Failed to find next question container');
                    return;
                }
                
                // Show the next container
                nextContainer.addClass('active');

                // Update progress bar and step indicators
                updateProgressBar();
                createStepIndicators();

                // Scroll to top of the active question
                $('html, body').animate({
                    scrollTop: $('.survey-question-container.active, .survey-personal-info.active').offset().top - 20
                }, 300);
                
                // For debugging
                console.log('Moved to question index:', currentQuestionIndex);
            }

            // Function to move to the previous question
            function moveToPreviousQuestion() {
                // Hide current question
                $('.survey-question-container.active').removeClass('active');

                // Decrement index
                currentQuestionIndex--;

                // Show previous question/section
                if (currentQuestionIndex === 0 && hasPersonalInfoSection) {
                    $('.survey-personal-info').addClass('active');
                } else {
                    if (hasPersonalInfoSection) {
                        $(`.survey-question-container:eq(${currentQuestionIndex - 1})`).addClass('active');
                    } else {
                        $(`.survey-question-container:eq(${currentQuestionIndex})`).addClass('active');
                    }
                }

                // Update progress bar and step indicators
                updateProgressBar();
                createStepIndicators();

                // Scroll to top of the active question
                $('html, body').animate({
                    scrollTop: $('.survey-question-container.active, .survey-personal-info.active').offset().top - 20
                }, 300);
            }

            // Function to update progress bar
            function updateProgressBar() {
                const progress = (currentQuestionIndex / totalSteps) * 100;
                $('#survey-progress').css('width', `${progress}%`);
            }

            // Initialize first section as active
            if (hasPersonalInfoSection) {
                $('.survey-personal-info').addClass('active');
            } else {
                $('.survey-question-container:first').addClass('active');
            }
        });
    </script>
@endsection
