GET {{ URL }}/api/factor
Content-Type: application/json
Accept: application/json

{
  "sort": "id|desc",
  "status": "done"
}

###

GET {{ URL }}/api/factor/123535
Content-Type: application/json
Accept: application/json

{
  "identify": "09354960060",
  "code": "6843"
}

###