GET {{ URL }}/factor
Content-Type: application/json
Accept: application/json
Authorization: Bearer 3|adh8fF2oGCn9uuSLfPKqnF1R9PNn7ZRuSY3bQULZ4ce93f44

###

GET {{ URL }}/factor/123535
Content-Type: application/json
Accept: application/json
Authorization: Bearer 3|adh8fF2oGCn9uuSLfPKqnF1R9PNn7ZRuSY3bQULZ4ce93f44

###