<?php

namespace Modules\User\app\Enums;

use BenSampo\Enum\Contracts\LocalizedEnum;
use BenSampo\Enum\Enum;

final class UserType extends Enum implements LocalizedEnum
{
    const Primary = 1;

    const Presenter = 2;

    public static function asArray(): array
    {
        return parent::asArray(); // TODO: Change the autogenerated stub
    }
}
