POST {{ URL }}/auth/login
Content-Type: application/json
Accept: application/json

{
  "identify": "09357515918"
}

###

POST {{ URL }}/auth/verify
Content-Type: application/json
Accept: application/json

{
  "identify": "09357515918",
  "code": "6159"
}

###

POST {{ URL }}/auth/dev-login
Content-Type: application/json
Accept: application/json