POST {{ URL }}/auth/login
Content-Type: application/json
Accept: application/json

{
  "identify": "zasadi@hotmail.com"
}

###

POST {{ URL }}/auth/verify
Content-Type: application/json
Accept: application/json

{
  "identify": "zasadi@hotmail.com",
  "code": "4675"
}

###

POST {{ URL }}/auth/dev-login
Content-Type: application/json
Accept: application/json