POST {{ URL }}/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "identify": "09354677626"
}

###

POST {{ URL }}/api/auth/verify
Content-Type: application/json
Accept: application/json

{
  "identify": "09354677626",
  "code": "3809"
}

###