GET {{ URL }}/api/blog
Content-Type: application/json
Accept: application/json

{
  "identify": "09354960060"
}

###

GET {{ URL }}/api/blog/test-blog
Content-Type: application/json
Accept: application/json

{
  "identify": "09354960060",
  "code": "6843"
}

###