# List Message
GET {{ URL }}/chat/5/message
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{ TOKEN }}
###

# Send Message
POST {{ URL }}/chat/5/message
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{ TOKEN }}

{
  "message":"Hi"
}
###

# Send Message
POST {{ URL }}/chat/4/message
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{ TOKEN }}

{
  "message":"Hi",
  "files": [8,9]
}
###

# Edit Message
# Delete Message
